### ISSUE TITLE
Multiple calls to lambda in Select call

### ISSUE THREAD

**Issue by mvcalder-xbk** [artpaul/clickhouse-cpp#100]
Can the lambda in an Execute / Select call be called an arbitrary number of times? Experimenting, I see it called twice, once with columns but no rows and a second time with data. If a query happened to return a lot of data should my lambda be prepared to be called multiple times with rows? Does it need to be thread safe or are calls to the lambda sequential? Thanks for any guidance,

Matt

**Comment by artpaul** [comment]
Hi Matt,
1. the server sends data block by block. Usually, if the replay doesn't have a lot of data, the lambda called twice in the way you mentioned. But in case of a lot of data, more than two calls are possible.
2. Each instance of Client class runs in a single thread, so If you don't share one lambda between different clients it not need to be thread-safe.

**Comment by mvcalder-xbk** [comment]
That makes sense, I was wondering how order could be preserved if it was multi-threaded, good to know it's not a problem. Thank you,

Matt
