### ISSUE TITLE
Error including with Cmake

### ISSUE THREAD

**Issue by feribg** [artpaul/clickhouse-cpp#102]
Im trying to include the C++ client as usual as a git dependency with Cmake but it fails with a weird error. This seems to have started to happen recently, is the `Network` typo intentional ?

```
/tmp/tmp.F2LbG6n01a/cmake-build-debug-remote-host/_deps/extern_clickhouse-src/clickhouse/columns/../base/socket.h:106: undefined reference to `clickhouse::NetrworkInitializer::NetrworkInitializer()'
```

```
FetchContent_Declare(
        extern_clickhouse
        GIT_REPOSITORY https://github.com/artpaul/clickhouse-cpp
)

FetchContent_GetProperties(extern_clickhouse)

if (NOT extern_clickhouse_POPULATED)
    FetchContent_Populate(extern_clickhouse)
    add_subdirectory(
            ${extern_clickhouse_SOURCE_DIR}
            ${extern_clickhouse_BINARY_DIR}
            EXCLUDE_FROM_ALL)
endif ()

message("Clickhouse version ${extern_clickhouse_VERSION} include folder: ${extern_clickhouse_SOURCE_DIR}")

FetchContent_GetProperties(extern_clickhouse)

target_link_libraries(exporter ${CMAKE_DL_LIBS} ${Boost_LIBRARIES} ${extern_clickhouse_LIBRARIES})
target_include_directories(exporter PRIVATE 
${extern_clickhouse_SOURCE_DIR})
```

**Comment by artpaul** [comment]
Hi,
- Typo is not intentional.
- The constructor of the class defined in socket.cpp and everything should work fine.

**Comment by feribg** [comment]
Is the most efficient way to insert into CH with this client. Im processing big binary files and I want to dump them into CH as fast as possible, is this client the fastest option or theres a way to format them in binary that will be faster to consume ?

**Comment by artpaul** [comment]
Well, according to the documentation, c++ library is using "The most efficient format."
https://clickhouse.tech/docs/en/interfaces/formats/#native 
But filling the Block structure may be a bottleneck because of memory allocation.

**Comment by feribg** [comment]
@artpaul Any way to work with this format directly, the docs basically say you aren't supposed to and leave it at that. For example create files in this format and load them on another machine or locally (memmap). Does the client optimize when there's a local connection or still goes through TCP? Thanks!

**Comment by artpaul** [comment]
I think it is possible to write some functions to build such files. And extend the client to work with them. I will try it. Please ping me back in two days if there will be no news from my side.

> Does the client optimize when there's a local connection or still goes through TCP?

No.

**Comment by feribg** [comment]
Thank you! 

Also to that point:
> But filling the Block structure may be a bottleneck because of memory allocation.

The `block` and `column` are basically buffers, right. Can you reuse the those. I didn't see a method called `reset` or anything like that to keep a fixed number of blocks and columns allocated and just reuse them similarly to buffers.
