### ISSUE TITLE
Retry mechanism

### ISSUE THREAD

**Issue by vpoinot** [artpaul/clickhouse-cpp#111]
I see there is a retry mechanism implemented at the moment, but it does not behave as I would have expected. Assuming the ping_before_query option is set, there is a RetryGuard before each call into the db. But with the current implementation, this RetryGuard will only try to reconnect once, no matter what is the value for send_retries.
I would have expected that the client tries to reconnect as many times as specified by send_retries.
My intent was to use this retry mechanism to have clickhouse-cpp try to reconnect to the server in case the connection was dropped for some reason: server restarted, temporary network failure, etc. My idea was just to retry every 10s for 6 times for instance, but that would not work with the current implementation. Is this the intended behaviour or a bug?  At first sight, it seems to me that removing the "if (!ok) throw" part would do the job...

**Comment by artpaul** [comment]
Thanks for pointing that out. The problem will not be fixed if we just remove "if (!ok) throw" but we need to compare `i` with `send_retries` before throwing an exception.
