### ISSUE TITLE
Failure when block size exceeds compressed packet limit

### ISSUE THREAD

**Issue by v5r** [artpaul/clickhouse-cpp#17]
Hi,

there is a problem where the client hangs while receiving data, if the size of a single block exceeds the server's 1MiB limit for compressed packets. In that case, the data for a single block is split up into multiple compressed packets, which the client does not handle correctly. The client then hangs in `CodedInputStream::ReadRaw`, as it attempts to read more data than was loaded into the ArrayInput in `Client::Impl::ReceiveData`.

**Comment by artpaul** [comment]
Fixed.

**Comment by v5r** [comment]
Yes, it's working correctly now, thanks!
