### ISSUE TITLE
async interface

### ISSUE THREAD

**Issue by silviucpp** [artpaul/clickhouse-cpp#21]
Hello,

Does the driver support any async interface (caller thread is not blocked and when a response is available a callback is called).

I want to implement an erlang binding in top of this library but I need to be able to use an async interface

Silviu

**Comment by artpaul** [comment]
Hello,
currently is no, but I will think about it.

**Comment by silviucpp** [comment]
Thanks, this will be a huge plus to the driver.

**Comment by silviucpp** [comment]
Will be this scheduled soon or there is no plan for this currently ? I'm asking because I want to do an erlang binding for this library and I want to know if I wait for async support or use only some parts related to protocol and implement myself in erlang the transport layer part.

Silviu

**Comment by artpaul** [comment]
I will have some free time in next two weeks. So I'll try to implement this feature.

**Comment by silviucpp** [comment]
Thanks a lot

Silviu

**Comment by silviucpp** [comment]
Hello Pavel,

I see you started working on the async interface. you are planning to have something implemented soon ? or it will take more time ?

**Comment by silviucpp** [comment]
Hello @artpaul,

Do you still have plans for supporting this async interface ? this will open the gates for building wrappers for other languages as well like js and erlang.

I'm opened to work on the erlang port and I can take two approaches:

1. if you create an async interface I can use that
2.if you don't have plans for it I can use only the classes used to encode decode the native protocol from your project and implement the tcp communication from erlang.

I will appreciate if you can share if async it's still in plan or not

Silviu

**Comment by alexey-milovidov** [comment]
@artpaul is no longer maintaining this library and async interface is not in plans.
Better to go with the second approach.

**Comment by silviucpp** [comment]
alexey-milovidov thanks for feedback . But at least the library is maintained by yandex team or it's an outdated project?

**Comment by alexey-milovidov** [comment]
It is maintained by Yandex.
