### ISSUE TITLE
What is communication protocol between driver and Clickhouse?

### ISSUE THREAD

**Issue by egorlitvinenko** [artpaul/clickhouse-cpp#23]

**Comment by artpaul** [comment]
Could you provide more information about you question?

**Comment by egorlitvinenko** [comment]
Of course, I mean, that clickhouse client written in cpp uses native protocol according to documentation. Unlike Java JDBC driver uses HTTP interface over clickhouse. What is using here?

**Comment by artpaul** [comment]
Yes, this client uses native protocol over tcp.

**Comment by egorlitvinenko** [comment]
Ok, thanks.
