### ISSUE TITLE
Strong typed exceptions for table does not exists and database does not exists

### ISSUE THREAD

**Issue by pavel-odintsov** [artpaul/clickhouse-cpp#24]
Hello!

I'm looking for some ways to automatically create databases and tables when I want to insert data to them. Right now I use try/catch approach and check description of std::exception to apply different logic.

After some investigation I discovered that CH has slightly different errors in these cases:
```
"DB::Exception: Database " + clickhouse_database_name + " doesn't exist"; 
"DB::Exception: Table " + full_table_name + " doesn't exist.";
```

As you can see, this format is not so consistent (even about "dot" at the end of the line) and I'm looking for some enough reliable way to detect these cases.

What about an idea to implement special types of exceptions for these cases and isolate "strpos" logic inside a library?

**Comment by artpaul** [comment]
I don't think that we should rely on exception message. Will be better to use exception codes. Of course it's good idea to implement this logic inside library.

**Comment by pavel-odintsov** [comment]
Yep, good idea. It also works for my case.

**Comment by artpaul** [comment]
Please take a look at this - https://github.com/artpaul/clickhouse-cpp/commit/5f39c1088dc52872e72c4292a027611e28027c85

**Comment by artpaul** [comment]
@pavel-odintsov Is it fits for you needs?

**Comment by pavel-odintsov** [comment]
Thank you so much! IT did what I want! :)
