### ISSUE TITLE
C++11 doesnt compile

### ISSUE THREAD

**Issue by yctn** [artpaul/clickhouse-cpp#28]
i tested and i cant compile it. im getting errors like:

-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /root/c/clickhouse-cpp/build
root@debian:~/c/clickhouse-cpp/build# make
Scanning dependencies of target lz4-lib
[  3%] Building C object contrib/lz4/CMakeFiles/lz4-lib.dir/lz4.c.o
[  7%] Building C object contrib/lz4/CMakeFiles/lz4-lib.dir/lz4hc.c.o
Linking C static library liblz4-lib.a
[  7%] Built target lz4-lib
Scanning dependencies of target cityhash-lib
[ 11%] Building CXX object contrib/cityhash/CMakeFiles/cityhash-lib.dir/city.cc.o
Linking CXX static library libcityhash-lib.a
[ 11%] Built target cityhash-lib
Scanning dependencies of target clickhouse-cpp-lib
[ 14%] Building CXX object clickhouse/CMakeFiles/clickhouse-cpp-lib.dir/base/coded.cpp.o
In file included from /usr/include/c++/4.9/cstdint:35:0,
                 from /root/c/clickhouse-cpp/clickhouse/base/input.h:4,
                 from /root/c/clickhouse-cpp/clickhouse/base/coded.h:3,
                 from /root/c/clickhouse-cpp/clickhouse/base/coded.cpp:1:
/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \

im running debian 8(jessie)

i manualy added: -std=c++11 in a few places and then it compiled. im no c++ expert but i think something is wrong with ur makefile or something

**Comment by artpaul** [comment]
Hi!
Am I understand correct what you succeeded in compilation with adding "-std=c++11" option?
What wil heppen if you just replace
USE_CXX11()
with
SET (CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}")
here:
https://github.com/artpaul/clickhouse-cpp/blob/master/CMakeLists.txt#L8
?

**Comment by Th3HolyMoose** [comment]
Hi, I am the one who assisted yctn with compiling. I am getting the same issue on my Debian system, v 8.3. 

Unfortunately, your suggested fix did not work for me, because it's overwriting that setting a few lines later in the same CMakeLists.txt. Fix was to simply add ${CMAKE_CXX_FLAGS} to the later SET(CMAKE_CXX_FLAGS...) as you can see below. 

`CMAKE_MINIMUM_REQUIRED(VERSION 3.0.2)

INCLUDE (cmake/cpp11.cmake)
INCLUDE (cmake/subdirs.cmake)

PROJECT (CLICKHOUSE-CLIENT)

    #USE_CXX11()
    SET (CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}")

    IF (UNIX)
        IF (APPLE)
            SET (CMAKE_CXX_FLAGS "-Wall -Wextra -Werror ${CMAKE_CXX_FLAGS}")
        ELSE ()
            SET (CMAKE_CXX_FLAGS "-pthread -Wall -Wextra -Werror ${CMAKE_CXX_FLAGS}")
        ENDIF ()
        SET (CMAKE_EXE_LINKER_FLAGS, "-lpthread")
    ENDIF ()

    INCLUDE_DIRECTORIES(.)
    INCLUDE_DIRECTORIES(contrib)

    SUBDIRS (
        clickhouse
        contrib/cityhash
        contrib/gtest
        contrib/lz4
        tests/simple
        ut
    )
`

With this CMakeLists.txt the project compile fine, without having to edit any flags.make like we did before!
