### ISSUE TITLE
How can I save select datas to a vector and return?

### ISSUE THREAD

**Issue by snowzjy** [artpaul/clickhouse-cpp#30]
Hi!

I read the Readme, and found the code:
/// Select values inserted in the previous step.
client.Select("SELECT id, name FROM test.numbers", [] (const Block& block)
    {
        for (size_t i = 0; i < block.GetRowCount(); ++i) {
            std::cout << block[0]->As<ColumnUInt64>()->At(i) << " "
                      << block[1]->As<ColumnString>()->At(i) << "\n";
        }
    }
);

This function is a SelectCallback and output to std::cout, but how can I select datas to a vector and return from SelectCallback?
I'm very like this database.If anyone can replay this issues, I will be very grateful!

**Comment by artpaul** [comment]
Hi, 
this is very simple since Select runs synchronously. Just pass a vector as a lambda's param and fill it.
```cpp
using namespace std;
vector<pair<int, string>> data;
client.Select("SELECT id, name FROM test.numbers", [&data] (const Block& block) {
  for (size_t i = 0; i < block.GetRowCount(); ++i) {
  data.push_back(
    make_pair(
      block[0]->As<ColumnUInt64>()->At(i), 
      block[1]->As<ColumnString>()->At(i)));
}
);
```

**Comment by snowzjy** [comment]
Thanks!
The design is very concise. I know how to use it now!
