### ISSUE TITLE
Difference between dateTime and date due timezone issues

### ISSUE THREAD

**Issue by pavel-odintsov** [artpaul/clickhouse-cpp#38]
Hello!

I have following code:
```
time_t seconds_epoch = time(NULL);

auto packet_date = std::make_shared<clickhouse::ColumnDate>();
auto date_time = std::make_shared<clickhouse::ColumnDateTime>();

packet_date->Append(seconds_epoch);
date_time->Append(seconds_epoch);

block.AppendColumn("packetDateTime", date_time);
block.AppendColumn("packetDate", packet_date);
```

According to https://github.com/artpaul/clickhouse-cpp/commit/9b51eb202b23b035c68e3402494feb135a6fcdee#diff-1b33440a9bf851c09ae96d0f9f76a82bR11 library could convert my datetime correctly to date.

But on the server with timezone UTC+2 we see following things:
```
metricDateTime      | metricDate
2017-12-10 00:23:05 │ 2017-12-09 
2017-12-10 00:23:06 │ 2017-12-09 
2017-12-10 00:23:08 │ 2017-12-09 
2017-12-10 00:23:09 │ 2017-12-09 
2017-12-10 00:23:10 │ 2017-12-09 
```

Looks like metricDateTime uses local time (UTC+2) but metricDate uses UTC+0.

Do you have any idea how we could handle this case properly? 

BTW, we do not use use_client_time_zone and use library defaults.

**Comment by artpaul** [comment]
Or may be not. If you do the following select:
`select metricDateTime, toDate(metricDateTime) from ...` 
you will get correct values. And the real problem is that it's wrong to get the current day by simply dividing the current timestamp by 86400.

**Comment by pavel-odintsov** [comment]
Hello!

Yes, we could use this approach but it does not work well for us. We use filtering by date to reduce the amount of data for precise filtering by DateTime.

**Comment by pavel-odintsov** [comment]
Hello!

Sorry for bothering you, but it's still an issue for us. Do you have any ideas about proper implementation of this calculation with timezone information?

Thank you!

**Comment by tdingus** [comment]
Since you have epoch time, you may save the epoch time in the database. Will the following work for you?

SELECT toString(toDateTime(1512861785), 'Africa/Blantyre') // utc+2
  toString(toDateTime(1512861785), \'Africa/Blantyre\')
  2017-12-10 01:23:05                                   │

SELECT toString(toDateTime(1512861785), 'Antarctica/Mawson')
  toString(toDateTime(1512861785), \'Antarctica/Mawson\')
  2017-12-10 04:23:05

**Comment by pavel-odintsov** [comment]
Hello!

Unfortunately, this option does not work for me. I cannot ask Clickhouse for time conversation each time when I insert data. 

I insert tens of thousands rows per second and I need time for each.

**Comment by filimonov** [comment]
Use something like 
```
CREATE table name (
timestamp DateTime,
date Date DEFAULT toDate(timestamp) 
...
) ...
```

And don't insert date manually at all (and don't list that column in insert statement), ClickHouse will fill it properly for you.

**Comment by pavel-odintsov** [comment]
Hello!

That's awesome! It works for me :)

Thank you!
