### ISSUE TITLE
insert to remote server takes long time

### ISSUE THREAD

**Issue by molchanov1983** [artpaul/clickhouse-cpp#39]
Hello. 
I have tested 2 inserts (1 million records) and i have question
This is a log

FROM REMOTE (FROM UKRAINE(client) TO USA(server))
2017.12.19 10:49:02.119056 [ 53 ] <Debug> MemoryTracker: Peak memory usage (for query): 4.00 KiB.
2017.12.19 10:49:02.119114 [ 53 ] <Debug> MemoryTracker: Peak memory usage (for user): 4.00 KiB.
2017.12.19 10:49:02.119129 [ 53 ] <Debug> MemoryTracker: Peak memory usage (total): 4.00 KiB.
2017.12.19 10:49:02.119172 [ 53 ] <Information> TCPHandler: Processed in 0.003 sec.
2017.12.19 10:49:02.692948 [ 53 ] <Debug> executeQuery:  INSERT INTO netflow_v4_5 VALUES
2017.12.19 10:51:23.798400 [ 53 ] <Trace> netflow.netflow_v4_5 (Data): Renaming temporary part tmp_insert_20171219_1_1_0 to 20171219_1_1_0.
2017.12.19 10:51:23.799289 [ 53 ] <Debug> MemoryTracker: Peak memory usage (for query): 64.89 MiB.
2017.12.19 10:51:23.799349 [ 53 ] <Debug> MemoryTracker: Peak memory usage (for user): 64.89 MiB.
2017.12.19 10:51:23.799374 [ 53 ] <Debug> MemoryTracker: Peak memory usage (total): 64.89 MiB.
2017.12.19 10:51:23.799416 [ 53 ] <Information> TCPHandler: Processed in 141.107 sec.

FROM LOCAL TO LOCAL
2017.12.19 11:00:25.506744 [ 29 ] <Debug> MemoryTracker: Peak memory usage (for query): 4.00 KiB.
2017.12.19 11:00:25.506927 [ 29 ] <Debug> MemoryTracker: Peak memory usage (for user): 4.00 KiB.
2017.12.19 11:00:25.506962 [ 29 ] <Debug> MemoryTracker: Peak memory usage (total): 4.00 KiB.
2017.12.19 11:00:25.507031 [ 29 ] <Information> TCPHandler: Processed in 0.004 sec.
2017.12.19 11:00:26.188507 [ 29 ] <Debug> executeQuery:  INSERT INTO netflow_v4_5 VALUES
2017.12.19 11:00:26.933624 [ 29 ] <Trace> netflow.netflow_v4_5 (Data): Renaming temporary part tmp_insert_20171219_1_1_0 to 20171219_1_1_0.
2017.12.19 11:00:26.934356 [ 29 ] <Debug> MemoryTracker: Peak memory usage (for query): 64.89 MiB.
2017.12.19 11:00:26.934454 [ 29 ] <Debug> MemoryTracker: Peak memory usage (for user): 64.89 MiB.
2017.12.19 11:00:26.934469 [ 29 ] <Debug> MemoryTracker: Peak memory usage (total): 64.89 MiB.
2017.12.19 11:00:26.934516 [ 29 ] <Information> TCPHandler: Processed in 0.746 sec.

In first execution executeQuery: takes 2.X minutes
In the second execution executeQuery: 0.746 sec

How to improve executeQuery in the first case ?
How to have more information to understand where the bottleneck is?
Thanks

**Comment by artpaul** [comment]
Because of long distance between UKRAINE and USA you may be need to tune up you tcp configuration.
Please google for "tuning tcp for high bandwidth delay networks".
Some relevant links:
http://www.kehlet.cx/articles/99.html
https://serverfault.com/questions/777805/tune-windows-for-high-latency-high-bandwidth-tcp-transfers
