### ISSUE TITLE
Does not compile with special compiler flags

### ISSUE THREAD

**Issue by inkrement** [artpaul/clickhouse-cpp#44]
A user of our RClickhouse package reported that the package does not compile when special compiler flags are used (`-march=native -mavx -mavx2 -msse4.2`)  https://github.com/IMSMWU/RClickhouse/issues/30. 

@artpaul This seems to be related to this package and not to our R-Code, thus I am opening a new issue here. Have you ever tried to compile it using similar flags or do you know, why this might not work?

**Comment by dselivanov** [comment]
Not all flags were used :-) any of the flags which explicitly add vectorization (starting from `msse4.2`)

**Comment by artpaul** [comment]
Fixed.

**Comment by inkrement** [comment]
Thanks!
