### ISSUE TITLE
always get hello as unexpected package when query or alter table. 

### ISSUE THREAD

**Issue by bwlee** [artpaul/clickhouse-cpp#56]
libc++abi.dylib: terminating with uncaught exception of type clickhouse::ServerException: DB::NetException: Unexpected packet Query received from client
libc++abi.dylib: terminating with uncaught exception of type clickhouse::ServerException: DB::Exception: Unexpected packet Hello received from client

It seems something changed in protocol with server, anything should I do to remove such handshake? 

Thanks in advance!

**Comment by artpaul** [comment]
Can't reproduce.
