### ISSUE TITLE
cannot execute show tables query

### ISSUE THREAD

**Issue by camviluong** [artpaul/clickhouse-cpp#58]
hello, I have execute a "show tables" to get tables in database, when i run this execute, it's loop

client.Select("show tables", [&](const clickhouse::Block &block)
{
...
});

**Comment by artpaul** [comment]
Can you describe your problem more precisely?
I've just added test for SHOW TABLES and everything works fine.

**Comment by camviluong** [comment]
These are my code:
clickhouse::Client client(clickhouse::ClientOptions()
	.SetHost(_szHost)
	.SetPingBeforeQuery(_bPingBeforeQuery)
	.SetDefaultDatabase(_szDatabase)
	.SetPort(9000)
	.SetPassword(_szPassword)
	.SetCompressionMethod(clickhouse::CompressionMethod::LZ4));

	**client.Select(szQuery, [&](const clickhouse::Block &block)**
	{
		for (size_t r = 0; r < block.GetRowCount(); ++r)
		{
		}
	});

when run client.Select, it throw a timeout exception: DB::NetException: Timeout execeeded while reading from socket
I have debug in throw the code and seen: it's timeout at the first time call ReceivePacket funtion

void Client::Impl::ExecuteQuery(Query query) {
    EnsureNull en(static_cast<QueryEvents*>(&query), &events_);

    if (options_.ping_before_query) {
        RetryGuard([this]() { Ping(); });
    }

    SendQuery(query.GetText());

    **while (ReceivePacket()) {**
        ;
    }
}

bool Client::Impl::ReceivePacket(uint64_t* server_packet) {
    uint64_t packet_type = 0;

    **if (!input_.ReadVarint64(&packet_type)) {**
        return false;
    }

**Comment by artpaul** [comment]
Have you ever had any successful queries with same connection params?

**Comment by camviluong** [comment]
Sorry, I have re-check again. There is a mistake because I use CompressMethod is None.
After I change the CompressMethod to LZ4, everything is fine. But is there something wrong with CompressMethod None?

**Comment by artpaul** [comment]
Everything should be fine because the CompressionMethod::None is a default compression method.
