### ISSUE TITLE
Unexpected behaviour with temporary tables

### ISSUE THREAD

**Issue by corrius** [artpaul/clickhouse-cpp#63]
I am creating temporary tables during the execution of a job, writing data and then copying it to the final table once I make sure that everything is fine.
The whole process is fine but the temporary tables are supposed to be deleted once I close the connection but the tables stay there, in the database I have specified with the connection, which is also odd as temporary tables aren´t supposed to have a database.
The remaining temporary tables are empty if I execute a count...

The query I use to create the table is:
CREATE TEMPORARY TABLE test_table_f55a142e4e164fc18ccaf0e2adf04b28 (...)
Then, several inserts and a final insert into the final table from the temporary one.

Is anyone else using temporary tables with the driver?

**Comment by artpaul** [comment]
Can't reproduce any problem with a temporary table. Maybe it was a server-side issue?
