### ISSUE TITLE
Problem multidimensional arrays Array(Array(Float64))

### ISSUE THREAD

**Issue by alexandroidus** [artpaul/clickhouse-cpp#64]
can't get array size from 

`CREATE TABLE IF NOT EXISTS test.array (arr Array(Array(Float64)))........`

```
for (size_t c = 0; c < block.GetRowCount(); ++c) {
  auto col = block[0]->As<ColumnArray>()->GetAsColumn(c); 
  std::cout << col->Size() << std::endl;
 }

```

`col->Size() - > Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`

**Comment by artpaul** [comment]
It should work now.
