### ISSUE TITLE
client Socket connections take too long if they don't exist

### ISSUE THREAD

**Issue by songhtdo** [artpaul/clickhouse-cpp#68]
Hi, how are you. Thank you for your work.
I have found that when connecting to a clickhouse server with a service state, the client is always dead.
It would be better if this strategy could control the number of attempts rather than deadlocks.

here: 
Client::Impl::Impl(const ClientOptions& opts)
and:
SOCKET SocketConnect(const NetworkAddress& addr)

**Comment by artpaul** [comment]
Please check this patch: https://github.com/artpaul/clickhouse-cpp/commit/99e3cf229a60e369b0a0683e8aeb7a1893f2e3b3

**Comment by songhtdo** [comment]
thank you.
