### ISSUE TITLE
Possible problems

### ISSUE THREAD

**Issue by shlyakpavel** [artpaul/clickhouse-cpp#78]
I've inspected the code with static code analyzer. Here's what I've found.

1. Exceptions should not be thrown in destructors.
https://github.com/artpaul/clickhouse-cpp/blob/3d7f9ca15e55829f9141728079a55f6a2f767082/clickhouse/base/compressed.cpp#L25

2. An object is used as an argument to its own method. Consider checking the first actual argument of the 'Append' function.
https://github.com/artpaul/clickhouse-cpp/blob/3d7f9ca15e55829f9141728079a55f6a2f767082/clickhouse/columns/uuid.cpp#L40

It would be great for someone familiar with the code to check this. Have a nice day!

**Comment by artpaul** [comment]
Thanks for your suggestions.
