### ISSUE TITLE
Build simple example on OSX fails

### ISSUE THREAD

**Issue by inkrement** [artpaul/clickhouse-cpp#8]
I tried to build the simple example on OSX like this

```
cd tests/simple
cmake .
```

> chris@Christians-MacBook-Air:~/Documents/clickhouse-cpp/tests/simple$ make
> [ 50%] Building CXX object CMakeFiles/simple-test.dir/main.cpp.o
> /Users/chris/Documents/clickhouse-cpp/tests/simple/main.cpp:1:10: fatal error: 'clickhouse/client.h' file not found
> #include <clickhouse/client.h>
>          ^
> 1 error generated.
> make[2]: *** [CMakeFiles/simple-test.dir/main.cpp.o] Error 1
> make[1]: *** [CMakeFiles/simple-test.dir/all] Error 2
> make: *** [all] Error 2

**Comment by artpaul** [comment]
Hi!
I reproduced it even on Linux. To fix it do the following:
```
1. cd ~/Documents/clickhouse-cpp
2. mkdir build
3. cd build
4. cmake ..
5. cd tests/simple
6. make
```

**Comment by inkrement** [comment]
thanks, works now! But why do you use this build directory? 

In my case it writes the output to the parent directory anyway...
```
chris@Christians-MacBook-Air:~/Documents/clickhouse-cpp$ cd build/
chris@Christians-MacBook-Air:~/Documents/clickhouse-cpp/build$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/chris/Documents/clickhouse-cpp
```

**Comment by artpaul** [comment]
Strange. Maybe it's some specific cmake's behaviour on  OSX. 
I'v just found some undocumented options of cmake to set specific output directory: http://stackoverflow.com/a/20611964
So try this inside build dir:
```cmake -B. -H..```

**Comment by artpaul** [comment]
> But why do you use this build directory?

1. You can't run cmake inside some specific source directory, as you did at first time, because it doesn’t have PROJECT directive as CMakeLists.txt in the root directory. 
2. It's good way to store all cmake's generated files in some specific directory and just ignore it out in .gitignore so git status won't show you any temporary files.

**Comment by inkrement** [comment]
ok thanks! I'll close this topic now
