### ISSUE TITLE
Support for LIVE VIEW TABLES and WATCH command?

### ISSUE THREAD

**Issue by dgrr** [artpaul/clickhouse-cpp#88]
For more information:
https://www.altinity.com/blog/2019/11/13/making-data-come-to-life-with-clickhouse-live-view-tables

**Comment by artpaul** [comment]
The current implementation is already capable of dealing with the WATCH query. It's better to use OnDataCancelable callback to be able to cancel a query. Here is the example compatible with the blog post:
```cpp
using namespace clickhouse;
auto print_data = [&stop_cond](const Block& block) {
  for (size_t i = 0; i < block.GetRowCount(); ++i) {
    std::cout << (*block[0]->As<ColumnInt64>())[i] << "\n";
  }
  return !stop_cond;
};
Client client{...};
client.Execute("SET allow_experimental_live_view = 1");
client.Select(
  Query("WATCH lv")
    .OnDataCancelable(print_data));
```
