### ISSUE TITLE
Error when the exception closes: Bad file descriptor

### ISSUE THREAD

**Issue by songhtdo** [artpaul/clickhouse-cpp#97]
Hi, Thank you again for your great work.
When an exception closes, the call to 
Client::Impl::~Impl() {
    Disconnect();
}
after throw "fail to send data: Bad file descriptor".

The reason may be that Disconnect was called first();
Flush() exception while continuing to destruct buffered_output_ object.

**Comment by artpaul** [comment]
Now it should work.
