### ISSUE TITLE
Linker or compiler errors depending on c++ standard

### ISSUE THREAD

**Issue by vincenzon** [artpaul/clickhouse-cpp#99]
I'm sure this is a problem of my own making, but I am looking for advice on how to work around it.

I am using the clickhouse-cpp client built using:

```
git clone https://github.com/ClickHouse/clickhouse-cpp.git
cd clickhouse-cpp
mkdir build 
cd build
cmake..
make
```

I am compiling a cython module as well as standalone c++ programs that use the clickhouse-cpp client. All of the standalone c++ programs are compiled with the `-std=c++17` flag and they work fine.

Initially, when building the cython module I was using the flag `-std=c++11` but that gave a compiler error:

```
/usr/local/include/clickhouse/types/types.h:51:14: error: 'As' function uses 'auto' type specifier without trailing return type
     auto* As() {
/usr/local/include/clickhouse/types/types.h:56:22: note: deduced return type only available with -std=c++14 or -std=gnu++14
```

which lead me to change the flag for the cython module to `-std=c++17`, which fixes the compiling issue. However, when I load the module I get an undefined symbol error:

```
 undefined symbol: _ZNK10clickhouse12ColumnString2AtEm
```

Using c++filt shows that symbol to be: `clickhouse::ColumnString::At(unsigned long) const`. So, I used nm to look at the symbols in libclickhouse-cpp-lib.so, and the only one that was close was:

```
000000000003dcc0 T _ZNK10clickhouse12ColumnString2AtB5cxx11Em
```

which c++filt demangles to: `clickhouse::ColumnString::At[abi:cxx11](unsigned long) const`. At this point I am confused. It looks like the missing symbol is due to that `abi:cxx11` tag but I'm not sure how that got created. 

Does this symbol mismatch look familiar and if so, how do I work around it? Thanks for any help,

Matt

**Comment by vincenzon** [comment]
Looks like I am hitting [this issue]([https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html).

**Comment by artpaul** [comment]
Hi,
as far as I can see you are using this version of clickhouse-cpp library: https://github.com/ClickHouse/clickhouse-cpp
because there is no "auto* As()" function in type.h:51
https://github.com/artpaul/clickhouse-cpp/blob/master/clickhouse/types/types.h#L51

**Comment by vincenzon** [comment]
I was having problems with the c++11 API as described in my link above. It was a separate dependency that I had compiled with the _GLIBCXX_USE_CXX11_ABI set to 0, nothing to do with the CH cpp libraries.
